from typing import Any, Dict, List, Optional, Literal
from typing_extensions import TypedDict


class AgentState(TypedDict):
    query: str                          # Original user message
    messages: List[Any]                 # List[Message] — conversation history
    route: Optional[Literal["text_to_sql", "rag", "hybrid", "conversation"]]
    analyzed: Optional[Any]             # AnalyzedQuery — set by execution nodes (not routing)
    tool_name: Optional[str]            # data tool name; None for conversation
    tool_result: Optional[str]          # Raw string output from the executed tool
    context: Optional[Dict[str, Any]]   # Structured context dict consumed by LLM
    sql_query: Optional[List[str]]       # SQL queries generated by text_to_sql tool
    tool_success: Optional[bool]
    tool_error_code: Optional[str]
    trace_id: str
    node_metrics: List[Dict[str, Any]]
    tool_calls: List[Dict[str, Any]]
    citations: List[Dict[str, Any]]
    plan: List[str]
    attempted_routes: List[str]
    iteration: int
    max_iterations: int
    needs_clarification: bool
    clarification_question: Optional[str]
    evaluation: Optional[Dict[str, Any]]
    response_attempts: int
    awaiting_approval: bool
    pending_action: Optional[Dict[str, Any]]
    response: Optional[str]             # Final LLM response text
