"""update default updated_at tables conversations messages

Revision ID: 46b1a595761c
Revises: ccb7baa9d8a0
Create Date: 2026-06-25 20:37:39.550475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46b1a595761c'
down_revision: Union[str, None] = 'ccb7baa9d8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        'fk_messages_conversation_id',
        'messages',
        'conversations',
        ['conversation_id'],
        ['id'],
    )
    op.drop_column('messages', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # Older deployments created this constraint without an explicit name, so
    # PostgreSQL assigned ``messages_conversation_id_fkey``. Support both that
    # legacy name and the deterministic name used by fresh installations.
    op.execute(
        'ALTER TABLE messages '
        'DROP CONSTRAINT IF EXISTS fk_messages_conversation_id'
    )
    op.execute(
        'ALTER TABLE messages '
        'DROP CONSTRAINT IF EXISTS messages_conversation_id_fkey'
    )
    # ### end Alembic commands ###
